sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'

addons:
  apt:
    package:
      - make

before_install:
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt test'
  - 'grunt build'
