sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - 'sudo apt-get install -y make g++'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt test'
